# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название:')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('img_small', models.ImageField(upload_to='books/%d-%m-%Y', verbose_name='Мал. изображение:')),
                ('img_big', models.ImageField(upload_to='books/%d-%m-%Y', verbose_name='Бол. изображение:')),
                ('download_link', models.URLField(max_length=300, verbose_name='Ссылка скачки:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации:')),
                ('likes', models.IntegerField(default=0, verbose_name='Кол. лайков:')),
                ('previews', models.IntegerField(default=0, verbose_name='Кол. просмотров:')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='my_site.Category', verbose_name='Категория(и):'),
        ),
    ]
