# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='my_site.Tag', verbose_name='Tags:'),
        ),
    ]
