"""empty message

Revision ID: 143ee26bebfe
Revises: 2e220b2d3e97
Create Date: 2017-10-04 10:55:26.485790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143ee26bebfe'
down_revision = '2e220b2d3e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
